name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://testdemo.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  REACT_APP_API_BASE_URL: http://localhost:3001
  VERSION: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  PACT_PROVIDER: pactflow-example-bi-directional-provider-postman
  PACTICIPANT: pactflow-example-bi-directional-consumer-playwright-js

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: "14"
      - name: Install
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Test
        run: make test
      - name: Publish pacts
        run: BRANCH=${GIT_REF:11} make publish_pacts

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Can I deploy?
        run: BRANCH=${GIT_REF:11} make can_i_deploy

  # Only deploy from main
  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Deploy
        run: BRANCH=${GIT_REF:11} make deploy
        # if: github.ref == 'refs/heads/main' # note this is set in our Makefile
